#Jekyll config file

#title of site
name: Danny Chapman

#description of site
description: Web designer and Open Government Fanboy Danny Chapman

#URL of site, include http://, do not include a trailing slash
url: http://localhost:4000
# url: http://dannychapman.com

#files to exclude, array
exclude: [ 'readme.md', 'php', 'node_modules' ]

#posts per page
paginate: 1

#number of items in RSS feed
rss_limit: 20

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true
